import { create } from "zustand";
import { playerApi } from "../api/player";
import {
  appendTracks,
  insertAfterCursor,
  moveInView as moveInViewOp,
  removeAt,
  type QueueShape,
} from "../lib/queueOps";
import { identityIndices, rotateToStart, shuffledIndices } from "../lib/shuffle";
import { usePlayerStore } from "./playerStore";
import type { RepeatMode, Track } from "../types";

export type { RepeatMode };

/** A saved session's queue, ready to be put back without playing anything. */
export interface QueueSnapshot {
  queue: Track[];
  shuffleOrder: number[];
  cursor: number;
  shuffle: boolean;
  repeat: RepeatMode;
  positionSecs: number;
}


interface QueueState {
  /** Base track list snapshot, in library order, from whichever list the user played from. */
  queue: Track[];
  /** Fixed random permutation of indices into `queue`. Only regenerated by `setQueue`
   * (a genuinely new playback context) - toggling shuffle on/off reuses it as-is, so
   * flipping the switch never reshuffles what's already queued. */
  shuffleOrder: number[];
  /** Index into `queue` of the currently playing track. */
  cursor: number;
  shuffle: boolean;
  repeat: RepeatMode;

  setQueue: (tracks: Track[], startTrack: Track) => Promise<void>;
  toggleShuffle: () => void;
  cycleRepeat: () => void;
  /** Direct setters, for anything that names the state it wants rather than
   * stepping to the next one - the desktop's media widget, notably. */
  setShuffle: (shuffle: boolean) => void;
  setRepeat: (repeat: RepeatMode) => void;
  playAtQueueIndex: (queueIndex: number) => Promise<void>;
  playNext: () => Promise<void>;
  playPrevious: () => Promise<void>;
  /** The queue in its currently active order (sequential or shuffled), rotated so the
   * playing track is always first - what the Queue view renders. */
  displayOrder: () => Track[];
  /** Path that would play after the current cursor, given repeat/shuffle - what gets
   * armed on the Rust side for gapless about-to-finish / crossfade pre-load. */
  peekNextPath: () => string | null;
  /** Called when the backend reports a gapless/crossfade transition that already
   * happened on its own; moves the cursor to match without re-invoking play. */
  syncCursorToPath: (path: string) => void;
  /** Puts a previous run's queue back without starting playback: the cursor's
   * track is loaded paused where it was left, so pressing play resumes rather
   * than restarts. */
  restore: (snapshot: QueueSnapshot) => Promise<void>;

  /** Adds to the end of the queue. Starts playing when there was nothing
   * queued at all, since "add to queue" on an idle player otherwise looks like
   * it did nothing. */
  enqueue: (tracks: Track[]) => Promise<void>;
  /** Adds so the tracks play right after the current one. */
  playNextInQueue: (tracks: Track[]) => Promise<void>;
  /** Drops one track. Removing the one playing moves on to whatever followed
   * it, or stops when it was the last. */
  removeFromQueue: (queueIndex: number) => Promise<void>;
  /** Moves an entry, addressed by its position in the queue view - which shows
   * the play order rotated so the playing track is first. */
  moveInView: (fromPosition: number, toPosition: number) => void;
}

/** The queue's index-bearing fields on their own, for the pure helpers in
 * `lib/queueOps` that do the actual bookkeeping. */
function shapeOf(state: QueueState): QueueShape<Track> {
  return { queue: state.queue, shuffleOrder: state.shuffleOrder, cursor: state.cursor };
}

function pushNextTrackToBackend(get: () => QueueState) {
  playerApi.setNextTrack(get().peekNextPath()).catch((e) => console.error("Failed to arm next track", e));
}

export const useQueueStore = create<QueueState>((set, get) => ({
  queue: [],
  shuffleOrder: [],
  cursor: -1,
  shuffle: false,
  repeat: "off",

  setQueue: async (tracks, startTrack) => {
    const startIndex = Math.max(
      0,
      tracks.findIndex((t) => t.path === startTrack.path),
    );
    const shuffleOrder = shuffledIndices(tracks.length);
    set({ queue: tracks, shuffleOrder, cursor: startIndex });
    await get().playAtQueueIndex(startIndex);
  },

  toggleShuffle: () => {
    get().setShuffle(!get().shuffle);
  },

  cycleRepeat: () => {
    const next: Record<RepeatMode, RepeatMode> = {
      off: "all",
      all: "one",
      one: "off",
    };
    get().setRepeat(next[get().repeat]);
  },

  setShuffle: (shuffle) => {
    if (get().shuffle === shuffle) return;
    set({ shuffle });
    pushNextTrackToBackend(get);
  },

  setRepeat: (repeat) => {
    if (get().repeat === repeat) return;
    set({ repeat });
    pushNextTrackToBackend(get);
  },

  playAtQueueIndex: async (queueIndex) => {
    const track = get().queue[queueIndex];
    if (!track) return;
    set({ cursor: queueIndex });
    await usePlayerStore.getState().play(track);
    pushNextTrackToBackend(get);
  },

  playNext: async () => {
    const { queue, cursor, repeat, shuffle, shuffleOrder } = get();
    if (queue.length === 0) return;
    if (repeat === "one") {
      await get().playAtQueueIndex(cursor);
      return;
    }
    const order = shuffle ? shuffleOrder : identityIndices(queue.length);
    const pos = order.indexOf(cursor);
    const nextPos = pos + 1;
    if (nextPos < order.length) {
      await get().playAtQueueIndex(order[nextPos]);
    } else if (repeat === "all") {
      await get().playAtQueueIndex(order[0]);
    } else {
      await usePlayerStore.getState().stop();
    }
  },

  playPrevious: async () => {
    const { queue, cursor, shuffle, shuffleOrder } = get();
    if (queue.length === 0) return;
    const order = shuffle ? shuffleOrder : identityIndices(queue.length);
    const pos = order.indexOf(cursor);
    await get().playAtQueueIndex(order[Math.max(0, pos - 1)]);
  },

  displayOrder: () => {
    const { queue, cursor, shuffle, shuffleOrder } = get();
    if (queue.length === 0) return [];
    const order = shuffle ? shuffleOrder : identityIndices(queue.length);
    return rotateToStart(order, cursor).map((i) => queue[i]);
  },

  peekNextPath: () => {
    const { queue, cursor, repeat, shuffle, shuffleOrder } = get();
    if (queue.length === 0 || cursor < 0) return null;
    if (repeat === "one") return queue[cursor]?.path ?? null;
    const order = shuffle ? shuffleOrder : identityIndices(queue.length);
    const pos = order.indexOf(cursor);
    const nextPos = pos + 1;
    if (nextPos < order.length) return queue[order[nextPos]]?.path ?? null;
    if (repeat === "all") return queue[order[0]]?.path ?? null;
    return null;
  },

  syncCursorToPath: (path) => {
    const index = get().queue.findIndex((t) => t.path === path);
    if (index === -1) return;
    set({ cursor: index });
    pushNextTrackToBackend(get);
  },

  restore: async ({ queue, shuffleOrder, cursor, shuffle, repeat, positionSecs }) => {
    set({ queue, shuffleOrder, cursor, shuffle, repeat });
    const track = queue[cursor];
    if (!track) return;
    await usePlayerStore.getState().restore(track, positionSecs);
    // Arm the follow-up exactly as starting playback normally would, so the
    // first transition after a restore isn't the one that stutters.
    pushNextTrackToBackend(get);
  },

  enqueue: async (tracks) => {
    if (tracks.length === 0) return;
    const wasEmpty = get().queue.length === 0;
    set(appendTracks(shapeOf(get()), tracks));
    if (wasEmpty) {
      await get().playAtQueueIndex(0);
      return;
    }
    pushNextTrackToBackend(get);
  },

  playNextInQueue: async (tracks) => {
    if (tracks.length === 0) return;
    const wasEmpty = get().queue.length === 0;
    set(insertAfterCursor(shapeOf(get()), tracks));
    if (wasEmpty) {
      await get().playAtQueueIndex(0);
      return;
    }
    pushNextTrackToBackend(get);
  },

  removeFromQueue: async (queueIndex) => {
    const state = get();
    // `shapeOf` builds a fresh object each call, so the no-op check has to
    // compare against the very one that was handed to `removeAt`.
    const before = shapeOf(state);
    const { shape, wasCurrent, nextCursor } = removeAt(before, queueIndex, state.shuffle);
    if (shape === before) return;
    set(shape);

    if (!wasCurrent) {
      pushNextTrackToBackend(get);
      return;
    }
    if (nextCursor >= 0) {
      await get().playAtQueueIndex(nextCursor);
    } else {
      await usePlayerStore.getState().stop();
      pushNextTrackToBackend(get);
    }
  },

  moveInView: (fromPosition, toPosition) => {
    const state = get();
    set(moveInViewOp(shapeOf(state), state.shuffle, fromPosition, toPosition));
    // What plays next may well have changed, and the backend still has the old
    // one armed.
    pushNextTrackToBackend(get);
  },
}));
