import { create } from "zustand";
import { playerApi } from "../api/player";
import { usePlayerStore } from "./playerStore";
import type { Track } from "../types";

export type RepeatMode = "off" | "all" | "one";

function shuffledIndices(length: number): number[] {
  const idx = Array.from({ length }, (_, i) => i);
  for (let i = idx.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [idx[i], idx[j]] = [idx[j], idx[i]];
  }
  return idx;
}

function identityIndices(length: number): number[] {
  return Array.from({ length }, (_, i) => i);
}

/** Rotates `order` so `startValue` is first, wrapping the rest around after it. */
function rotateToStart(order: number[], startValue: number): number[] {
  const p = order.indexOf(startValue);
  if (p <= 0) return order;
  return [...order.slice(p), ...order.slice(0, p)];
}

interface QueueState {
  /** Base track list snapshot, in library order, from whichever list the user played from. */
  queue: Track[];
  /** Fixed random permutation of indices into `queue`. Only regenerated by `setQueue`
   * (a genuinely new playback context) - toggling shuffle on/off reuses it as-is, so
   * flipping the switch never reshuffles what's already queued. */
  shuffleOrder: number[];
  /** Index into `queue` of the currently playing track. */
  cursor: number;
  shuffle: boolean;
  repeat: RepeatMode;

  setQueue: (tracks: Track[], startTrack: Track) => Promise<void>;
  toggleShuffle: () => void;
  cycleRepeat: () => void;
  playAtQueueIndex: (queueIndex: number) => Promise<void>;
  playNext: () => Promise<void>;
  playPrevious: () => Promise<void>;
  /** The queue in its currently active order (sequential or shuffled), rotated so the
   * playing track is always first - what the Queue view renders. */
  displayOrder: () => Track[];
  /** Path that would play after the current cursor, given repeat/shuffle - what gets
   * armed on the Rust side for gapless about-to-finish / crossfade pre-load. */
  peekNextPath: () => string | null;
  /** Called when the backend reports a gapless/crossfade transition that already
   * happened on its own; moves the cursor to match without re-invoking play. */
  syncCursorToPath: (path: string) => void;
}

function pushNextTrackToBackend(get: () => QueueState) {
  playerApi.setNextTrack(get().peekNextPath()).catch((e) => console.error("Failed to arm next track", e));
}

export const useQueueStore = create<QueueState>((set, get) => ({
  queue: [],
  shuffleOrder: [],
  cursor: -1,
  shuffle: false,
  repeat: "off",

  setQueue: async (tracks, startTrack) => {
    const startIndex = Math.max(
      0,
      tracks.findIndex((t) => t.path === startTrack.path),
    );
    const shuffleOrder = shuffledIndices(tracks.length);
    set({ queue: tracks, shuffleOrder, cursor: startIndex });
    await get().playAtQueueIndex(startIndex);
  },

  toggleShuffle: () => {
    set((s) => ({ shuffle: !s.shuffle }));
    pushNextTrackToBackend(get);
  },

  cycleRepeat: () => {
    const next: Record<RepeatMode, RepeatMode> = {
      off: "all",
      all: "one",
      one: "off",
    };
    set((s) => ({ repeat: next[s.repeat] }));
    pushNextTrackToBackend(get);
  },

  playAtQueueIndex: async (queueIndex) => {
    const track = get().queue[queueIndex];
    if (!track) return;
    set({ cursor: queueIndex });
    await usePlayerStore.getState().play(track);
    pushNextTrackToBackend(get);
  },

  playNext: async () => {
    const { queue, cursor, repeat, shuffle, shuffleOrder } = get();
    if (queue.length === 0) return;
    if (repeat === "one") {
      await get().playAtQueueIndex(cursor);
      return;
    }
    const order = shuffle ? shuffleOrder : identityIndices(queue.length);
    const pos = order.indexOf(cursor);
    const nextPos = pos + 1;
    if (nextPos < order.length) {
      await get().playAtQueueIndex(order[nextPos]);
    } else if (repeat === "all") {
      await get().playAtQueueIndex(order[0]);
    } else {
      await usePlayerStore.getState().stop();
    }
  },

  playPrevious: async () => {
    const { queue, cursor, shuffle, shuffleOrder } = get();
    if (queue.length === 0) return;
    const order = shuffle ? shuffleOrder : identityIndices(queue.length);
    const pos = order.indexOf(cursor);
    await get().playAtQueueIndex(order[Math.max(0, pos - 1)]);
  },

  displayOrder: () => {
    const { queue, cursor, shuffle, shuffleOrder } = get();
    if (queue.length === 0) return [];
    const order = shuffle ? shuffleOrder : identityIndices(queue.length);
    return rotateToStart(order, cursor).map((i) => queue[i]);
  },

  peekNextPath: () => {
    const { queue, cursor, repeat, shuffle, shuffleOrder } = get();
    if (queue.length === 0 || cursor < 0) return null;
    if (repeat === "one") return queue[cursor]?.path ?? null;
    const order = shuffle ? shuffleOrder : identityIndices(queue.length);
    const pos = order.indexOf(cursor);
    const nextPos = pos + 1;
    if (nextPos < order.length) return queue[order[nextPos]]?.path ?? null;
    if (repeat === "all") return queue[order[0]]?.path ?? null;
    return null;
  },

  syncCursorToPath: (path) => {
    const index = get().queue.findIndex((t) => t.path === path);
    if (index === -1) return;
    set({ cursor: index });
    pushNextTrackToBackend(get);
  },
}));
