// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	addMusicFolder: () => __TAURI_INVOKE<ScanReport>("add_music_folder"),
	getTracks: () => __TAURI_INVOKE<Track[]>("get_tracks").then((v) => (v.map(i=>({...i,duration_secs:i.duration_secs==null?i.duration_secs:i.duration_secs})) as typeof v)),
	getTrackCover: (path: string) => __TAURI_INVOKE<string | null>("get_track_cover", { path }),
	/**
	 *  Colors for the Now Playing gradient, taken from the same cached thumbnail
	 *  the cover art is served from - so this costs a small decode at most once per
	 *  track, off the UI thread, instead of decoding and quantizing in the webview.
	 */
	getTrackPalette: (path: string) => __TAURI_INVOKE<{
	vibrant: string,
	darkVibrant: string,
	muted: string,
	darkMuted: string,
} | null>("get_track_palette", { path }),
	updateTrackTags: (path: string, title: string, artist: string | null, album: string | null, trackNo: number | null, coverPath: string | null) => __TAURI_INVOKE<Track>("update_track_tags", { path, title, artist, album, trackNo, coverPath }).then((v) => (({...v,duration_secs:v.duration_secs==null?v.duration_secs:v.duration_secs}) as typeof v)),
	toggleFavorite: (trackId: number) => __TAURI_INVOKE<boolean>("toggle_favorite", { trackId }),
	getLyrics: (path: string) => __TAURI_INVOKE<{
	lines: LrcLine[],
} | null>("get_lyrics", { path }).then((v) => (v==null?v:({...v,lines:v.lines.map(i=>({...i,words:i.words==null?i.words:i.words.map(i=>i)}))}) as typeof v)),
	/**
	 *  Raw LRC text for the in-app editor to prefill (same tag-then-file source
	 *  priority as `get_lyrics`, but returns the unparsed text so edits round-trip
	 *  exactly, and is an empty string rather than null when nothing exists yet).
	 */
	getLyricsSourceText: (path: string) => __TAURI_INVOKE<string>("get_lyrics_source_text", { path }),
	saveLyrics: (path: string, content: string, storeInTag: boolean) => __TAURI_INVOKE<null>("save_lyrics", { path, content, storeInTag }),
	playTrack: (path: string) => __TAURI_INVOKE<null>("play_track", { path }),
	togglePlay: () => __TAURI_INVOKE<null>("toggle_play"),
	pausePlayback: () => __TAURI_INVOKE<null>("pause_playback"),
	seek: (positionSecs: number) => __TAURI_INVOKE<null>("seek", { positionSecs }),
	setVolume: (volume: number) => __TAURI_INVOKE<null>("set_volume", { volume }),
	stopPlayback: () => __TAURI_INVOKE<null>("stop_playback"),
	subscribePlaybackTicks: (channel: Channel<PlaybackTick>) => __TAURI_INVOKE<void>("subscribe_playback_ticks", { channel }),
	setNextTrack: (path: string | null) => __TAURI_INVOKE<null>("set_next_track", { path }),
	getPlaybackSettings: () => __TAURI_INVOKE<PlaybackSettings>("get_playback_settings").then((v) => (({...v,eqGains:v.eqGains.map(i=>i)}) as typeof v)),
	setCrossfadeSeconds: (secs: number) => __TAURI_INVOKE<void>("set_crossfade_seconds", { secs }),
	saveCrossfadeSeconds: (secs: number) => __TAURI_INVOKE<null>("save_crossfade_seconds", { secs }),
	setEqualizerBands: (gains: [number, number, number, number, number, number, number, number, number, number]) => __TAURI_INVOKE<null>("set_equalizer_bands", { gains: gains.map(i=>i) }),
	/**
	 *  Applies `tempo` live to whichever deck currently holds `path` (the audible
	 *  part of a drag) without touching the DB - called on every slider event.
	 */
	previewTrackTempo: (path: string, tempo: number) => __TAURI_INVOKE<void>("preview_track_tempo", { path, tempo }),
	/**
	 *  Persists a track's tempo to the DB - the frontend debounces this so a drag
	 *  doesn't write on every event; `preview_track_tempo` already handled the
	 *  live audio side immediately.
	 */
	setTrackTempo: (trackId: number, tempo: number) => __TAURI_INVOKE<null>("set_track_tempo", { trackId, tempo }),
	getTheme: () => __TAURI_INVOKE<Theme>("get_theme"),
	setTheme: (theme: Theme) => __TAURI_INVOKE<null>("set_theme", { theme }),
	getDefaultTheme: (mode: string) => __TAURI_INVOKE<Theme>("get_default_theme", { mode }),
	exportTheme: (path: string) => __TAURI_INVOKE<null>("export_theme", { path }),
	importTheme: (path: string) => __TAURI_INVOKE<Theme>("import_theme", { path }),
	getHotkeys: () => __TAURI_INVOKE<Hotkeys>("get_hotkeys"),
	setHotkeys: (hotkeys: Hotkeys) => __TAURI_INVOKE<null>("set_hotkeys", { hotkeys }),
	getPlaylists: () => __TAURI_INVOKE<Playlist[]>("get_playlists"),
	createPlaylist: (name: string) => __TAURI_INVOKE<Playlist>("create_playlist", { name }),
	renamePlaylist: (id: number, name: string) => __TAURI_INVOKE<null>("rename_playlist", { id, name }),
	deletePlaylist: (id: number) => __TAURI_INVOKE<null>("delete_playlist", { id }),
	getPlaylistTracks: (id: number) => __TAURI_INVOKE<Track[]>("get_playlist_tracks", { id }).then((v) => (v.map(i=>({...i,duration_secs:i.duration_secs==null?i.duration_secs:i.duration_secs})) as typeof v)),
	addTrackToPlaylist: (playlistId: number, trackId: number) => __TAURI_INVOKE<null>("add_track_to_playlist", { playlistId, trackId }),
	removeTrackFromPlaylist: (playlistId: number, trackId: number) => __TAURI_INVOKE<null>("remove_track_from_playlist", { playlistId, trackId }),
	reorderPlaylistTracks: (playlistId: number, trackIds: number[]) => __TAURI_INVOKE<null>("reorder_playlist_tracks", { playlistId, trackIds }),
};

/* Types */
export type Hotkeys = {
	playPause: string,
	seekForward: string,
	seekBackward: string,
	volumeUp: string,
	volumeDown: string,
	nextTrack: string,
	previousTrack: string,
	closeNowPlaying: string,
};

export type LrcLine = {
	time_secs: number,
	text: string,
	words: LrcWord[] | null,
};

export type LrcWord = {
	time_secs: number,
	text: string,
};

export type Lyrics = {
	lines: LrcLine[],
};

export type PlaybackSettings = {
	/**  0 = gapless (no fade), > 0 = crossfade duration in seconds. */
	crossfadeSecs: number,
	/**  10-band equalizer gains in dB, roughly -24..12 each. */
	eqGains: [number, number, number, number, number, number, number, number, number, number],
};

export type PlaybackTick = {
	is_playing: boolean,
	position_secs: number,
	duration_secs: number,
	path: string | null,
	/**
	 *  One-shot pulse: true on exactly the tick that observed a real End-Of-Stream
	 *  with nothing pre-rolled to follow it, so the frontend can decide whether to
	 *  advance the queue.
	 */
	ended: boolean,
	/**
	 *  One-shot pulse: set to the new path exactly on the tick that performed a
	 *  gapless or crossfade transition, so the frontend can sync its queue cursor
	 *  without re-invoking play (which would interrupt the seamless transition).
	 */
	auto_advanced_to: string | null,
};

export type Playlist = {
	id: number,
	name: string,
	track_count: number,
};

export type ScanReport = {
	added: number,
	updated: number,
	removed: number,
	errors: string[],
};

export type Theme = {
	background: string,
	sidebarBackground: string,
	playerBarBackground: string,
	cardBackground: string,
	cardHover: string,
	accentPrimary: string,
	accentSecondary: string,
	textPrimary: string,
	textSecondary: string,
	divider: string,
	progressTrack: string,
	progressFill: string,
	karaokeInactiveLine: string,
	karaokeActiveLine: string,
	karaokeActiveWordHighlight: string,
};

export type Track = {
	id: number,
	path: string,
	title: string,
	artist: string | null,
	album: string | null,
	duration_secs: number | null,
	track_no: number | null,
	is_favorite: boolean,
	/**  Playback speed multiplier without pitch shift; 1.0 = normal. */
	tempo: number,
};

/**  The four swatches the Now Playing background gradient is built from. */
export type TrackPalette = {
	vibrant: string,
	darkVibrant: string,
	muted: string,
	darkMuted: string,
};

