// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	addMusicFolder: () => __TAURI_INVOKE<ScanReport>("add_music_folder"),
	/**
	 *  Off the UI thread for the same reason as the scan and the cover decode: on
	 *  Linux/webkitgtk a synchronous command's IPC dispatch runs on the GTK main
	 *  thread, and serialising an entire library there freezes the window for as
	 *  long as it takes.
	 */
	getTracks: () => __TAURI_INVOKE<Track[]>("get_tracks").then((v) => (v.map(i=>({...i,duration_secs:i.duration_secs==null?i.duration_secs:i.duration_secs,last_played_at:i.last_played_at==null?i.last_played_at:i.last_played_at})) as typeof v)),
	getTrackCover: (path: string) => __TAURI_INVOKE<string | null>("get_track_cover", { path }),
	/**
	 *  Colors for the Now Playing gradient, taken from the same cached thumbnail
	 *  the cover art is served from - so this costs a small decode at most once per
	 *  track, off the UI thread, instead of decoding and quantizing in the webview.
	 */
	getTrackPalette: (path: string) => __TAURI_INVOKE<{
	vibrant: string,
	darkVibrant: string,
	muted: string,
	darkMuted: string,
} | null>("get_track_palette", { path }),
	/**
	 *  Rewrites the file's tags, which is blocking file I/O - and so has no
	 *  business running on the GTK main thread either.
	 */
	updateTrackTags: (path: string, title: string, artist: string | null, album: string | null, trackNo: number | null, coverPath: string | null) => __TAURI_INVOKE<Track>("update_track_tags", { path, title, artist, album, trackNo, coverPath }).then((v) => (({...v,duration_secs:v.duration_secs==null?v.duration_secs:v.duration_secs,last_played_at:v.last_played_at==null?v.last_played_at:v.last_played_at}) as typeof v)),
	toggleFavorite: (trackId: number) => __TAURI_INVOKE<boolean>("toggle_favorite", { trackId }),
	/**
	 *  Counts one listen. A single indexed UPDATE, so it stays synchronous - the
	 *  reason the two commands above went async is the work they do, not the fact
	 *  that they touch the database.
	 */
	recordPlay: (trackId: number) => __TAURI_INVOKE<null>("record_play", { trackId }),
	getLyrics: (path: string) => __TAURI_INVOKE<{
	lines: LrcLine[],
} | null>("get_lyrics", { path }).then((v) => (v==null?v:({...v,lines:v.lines.map(i=>({...i,words:i.words==null?i.words:i.words.map(i=>i)}))}) as typeof v)),
	/**
	 *  Raw LRC text for the in-app editor to prefill (same tag-then-file source
	 *  priority as `get_lyrics`, but returns the unparsed text so edits round-trip
	 *  exactly, and is an empty string rather than null when nothing exists yet).
	 */
	getLyricsSourceText: (path: string) => __TAURI_INVOKE<string>("get_lyrics_source_text", { path }),
	saveLyrics: (path: string, content: string, storeInTag: boolean) => __TAURI_INVOKE<null>("save_lyrics", { path, content, storeInTag }),
	/**
	 *  Looks the track's lyrics up on LRCLIB and returns the LRC text, or `None`
	 *  when nothing convincing was found.
	 * 
	 *  Deliberately an explicit action rather than something that happens on every
	 *  track change: this is the only outbound request the app makes, and a local
	 *  music player reaching for the network unprompted is a surprise. Saving is
	 *  left to the caller too, so the existing tag-or-sidecar choice still applies.
	 */
	fetchOnlineLyrics: (path: string) => __TAURI_INVOKE<string | null>("fetch_online_lyrics", { path }),
	playTrack: (path: string) => __TAURI_INVOKE<null>("play_track", { path }),
	togglePlay: () => __TAURI_INVOKE<null>("toggle_play"),
	pausePlayback: () => __TAURI_INVOKE<null>("pause_playback"),
	seek: (positionSecs: number) => __TAURI_INVOKE<null>("seek", { positionSecs }),
	setVolume: (volume: number) => __TAURI_INVOKE<null>("set_volume", { volume }),
	stopPlayback: () => __TAURI_INVOKE<null>("stop_playback"),
	subscribePlaybackTicks: (channel: Channel<PlaybackTick>) => __TAURI_INVOKE<void>("subscribe_playback_ticks", { channel }),
	setNextTrack: (path: string | null) => __TAURI_INVOKE<null>("set_next_track", { path }),
	getPlaybackSettings: () => __TAURI_INVOKE<PlaybackSettings>("get_playback_settings").then((v) => (({...v,eqGains:v.eqGains.map(i=>i)}) as typeof v)),
	setCrossfadeSeconds: (secs: number) => __TAURI_INVOKE<void>("set_crossfade_seconds", { secs }),
	saveCrossfadeSeconds: (secs: number) => __TAURI_INVOKE<null>("save_crossfade_seconds", { secs }),
	setEqualizerBands: (gains: [number, number, number, number, number, number, number, number, number, number]) => __TAURI_INVOKE<null>("set_equalizer_bands", { gains: gains.map(i=>i) }),
	/**
	 *  Applies `tempo` live to whichever deck currently holds `path` (the audible
	 *  part of a drag) without touching the DB - called on every slider event.
	 */
	previewTrackTempo: (path: string, tempo: number) => __TAURI_INVOKE<void>("preview_track_tempo", { path, tempo }),
	/**
	 *  Persists a track's tempo to the DB - the frontend debounces this so a drag
	 *  doesn't write on every event; `preview_track_tempo` already handled the
	 *  live audio side immediately.
	 */
	setTrackTempo: (trackId: number, tempo: number) => __TAURI_INVOKE<null>("set_track_tempo", { trackId, tempo }),
	/**
	 *  Loads `path` paused at `position_secs`. This is session restore: the app
	 *  comes back with the track it was closed on sitting exactly where it was,
	 *  without starting to play by itself.
	 */
	restoreTrack: (path: string, positionSecs: number) => __TAURI_INVOKE<null>("restore_track", { path, positionSecs }),
	getSession: () => __TAURI_INVOKE<Session>("get_session"),
	/**
	 *  Replaces the queue half of the session. Split from `set_session_progress`
	 *  because the queue is the big, rarely-changing part - playing a whole library
	 *  as one queue is one path per track, and it must not cross the IPC boundary
	 *  again every few seconds just because the playhead moved.
	 */
	setSessionQueue: (queuePaths: string[], shuffleOrder: number[]) => __TAURI_INVOKE<void>("set_session_queue", { queuePaths, shuffleOrder }),
	/**
	 *  The cheap, frequently-updated half: where playback is and how it's
	 *  configured. In-memory only - `save_session` owns the disk write.
	 */
	setSessionProgress: (cursor: number, positionSecs: number, volume: number, shuffle: boolean, repeat: RepeatMode) => __TAURI_INVOKE<void>("set_session_progress", { cursor, positionSecs, volume, shuffle, repeat }),
	/**
	 *  Flushes the in-memory session to disk. A no-op when nothing has changed
	 *  since the last flush.
	 */
	saveSession: () => __TAURI_INVOKE<null>("save_session"),
	/**
	 *  Whether the frontend should draw its own window controls, decided from the
	 *  session the app was launched into. See `domain::window_chrome`.
	 */
	getWindowControlsVisible: () => __TAURI_INVOKE<boolean>("get_window_controls_visible"),
	getTheme: () => __TAURI_INVOKE<Theme>("get_theme"),
	setTheme: (theme: Theme) => __TAURI_INVOKE<null>("set_theme", { theme }),
	getS3Config: () => __TAURI_INVOKE<S3Config>("get_s3_config"),
	setS3Config: (config: S3Config) => __TAURI_INVOKE<null>("set_s3_config", { config }),
	/**  Keys go to the system keyring, never to a config file. */
	setS3Credentials: (accessKey: string, secretKey: string) => __TAURI_INVOKE<null>("set_s3_credentials", { accessKey, secretKey }),
	forgetS3Credentials: () => __TAURI_INVOKE<void>("forget_s3_credentials"),
	hasS3Credentials: () => __TAURI_INVOKE<boolean>("has_s3_credentials"),
	/**  One cheap request: proves the endpoint, the bucket and the keys work. */
	checkS3Connection: () => __TAURI_INVOKE<null>("check_s3_connection"),
	/**  Runs the whole sync. Progress arrives as `sync-progress` events. */
	syncNow: () => __TAURI_INVOKE<SyncOutcome>("sync_now"),
	getThemeSource: () => __TAURI_INVOKE<ThemeSource>("get_theme_source"),
	/**
	 *  Switch between the user's own palette and the desktop shell's. Switching to
	 *  the system palette doesn't touch the manual one, so coming back restores it.
	 */
	setThemeSource: (source: ThemeSource) => __TAURI_INVOKE<Theme>("set_theme_source", { source }),
	/**
	 *  Whether there is a shell palette to follow at all - the setting is pointless
	 *  without one.
	 */
	systemThemeAvailable: () => __TAURI_INVOKE<boolean>("system_theme_available"),
	getDefaultTheme: (mode: string) => __TAURI_INVOKE<Theme>("get_default_theme", { mode }),
	exportTheme: (path: string) => __TAURI_INVOKE<null>("export_theme", { path }),
	importTheme: (path: string) => __TAURI_INVOKE<Theme>("import_theme", { path }),
	getHotkeys: () => __TAURI_INVOKE<Hotkeys>("get_hotkeys"),
	setHotkeys: (hotkeys: Hotkeys) => __TAURI_INVOKE<null>("set_hotkeys", { hotkeys }),
	getPlaylists: () => __TAURI_INVOKE<Playlist[]>("get_playlists"),
	createPlaylist: (name: string) => __TAURI_INVOKE<Playlist>("create_playlist", { name }),
	renamePlaylist: (id: number, name: string) => __TAURI_INVOKE<null>("rename_playlist", { id, name }),
	deletePlaylist: (id: number) => __TAURI_INVOKE<null>("delete_playlist", { id }),
	getPlaylistTracks: (id: number) => __TAURI_INVOKE<Track[]>("get_playlist_tracks", { id }).then((v) => (v.map(i=>({...i,duration_secs:i.duration_secs==null?i.duration_secs:i.duration_secs,last_played_at:i.last_played_at==null?i.last_played_at:i.last_played_at})) as typeof v)),
	addTrackToPlaylist: (playlistId: number, trackId: number) => __TAURI_INVOKE<null>("add_track_to_playlist", { playlistId, trackId }),
	removeTrackFromPlaylist: (playlistId: number, trackId: number) => __TAURI_INVOKE<null>("remove_track_from_playlist", { playlistId, trackId }),
	reorderPlaylistTracks: (playlistId: number, trackIds: number[]) => __TAURI_INVOKE<null>("reorder_playlist_tracks", { playlistId, trackIds }),
};

/* Types */
export type Hotkeys = {
	playPause: string,
	seekForward: string,
	seekBackward: string,
	volumeUp: string,
	volumeDown: string,
	nextTrack: string,
	previousTrack: string,
	closeNowPlaying: string,
};

export type LrcLine = {
	time_secs: number,
	text: string,
	words: LrcWord[] | null,
};

export type LrcWord = {
	time_secs: number,
	text: string,
};

export type Lyrics = {
	lines: LrcLine[],
};

/**
 *  A GStreamer error message that reached one of the decks, on its way to a
 *  toast in the UI.
 */
export type PlaybackError = {
	/**  The file that failed, when the deck that raised it had one loaded. */
	path: string | null,
	message: string,
	/**
	 *  True when the failure hit the deck that was actually playing - audio has
	 *  stopped and the queue needs to move on. False when it was the pre-rolled
	 *  standby deck, where only the pre-load was lost and playback continues.
	 */
	fatal: boolean,
};

export type PlaybackSettings = {
	/**  0 = gapless (no fade), > 0 = crossfade duration in seconds. */
	crossfadeSecs: number,
	/**  10-band equalizer gains in dB, roughly -24..12 each. */
	eqGains: [number, number, number, number, number, number, number, number, number, number],
};

export type PlaybackTick = {
	is_playing: boolean,
	position_secs: number,
	duration_secs: number,
	path: string | null,
	/**
	 *  One-shot pulse: true on exactly the tick that observed a real End-Of-Stream
	 *  with nothing pre-rolled to follow it, so the frontend can decide whether to
	 *  advance the queue.
	 */
	ended: boolean,
	/**
	 *  One-shot pulse: set to the new path exactly on the tick that performed a
	 *  gapless or crossfade transition, so the frontend can sync its queue cursor
	 *  without re-invoking play (which would interrupt the seamless transition).
	 */
	auto_advanced_to: string | null,
	/**
	 *  One-shot pulse: an error drained off a deck's bus this tick. Everything
	 *  that wasn't EOS used to be discarded here, so a missing codec or an
	 *  unreadable file left playback silently stalled with nothing said and the
	 *  queue never advancing.
	 */
	error: PlaybackError | null,
};

export type Playlist = {
	id: number,
	name: string,
	track_count: number,
};

export type RepeatMode = "off" | "all" | "one";

/**
 *  Where the library is mirrored. Keys are never stored here - they live in the
 *  system keyring (see data/s3/creds.rs).
 */
export type S3Config = {
	/**  Empty means AWS in the given region */
	endpoint?: string,
	region?: string,
	bucket?: string,
	/**  Everything Muzon writes lives under this prefix */
	prefix?: string,
	/**  MinIO and most self-hosted servers need path-style addressing */
	pathStyle?: boolean,
};

export type ScanReport = {
	added: number,
	updated: number,
	removed: number,
	errors: string[],
};

/**
 *  What the app puts back after a restart: the queue you were listening to, the
 *  track you were on and how far into it, plus the switches that shape playback.
 *  Restored paused - an app that starts blaring the moment it launches is not
 *  what anyone means by "remember where I was".
 * 
 *  Tracks are stored as paths rather than row ids so a re-scan that renumbers
 *  the library (or a database rebuilt from scratch) still restores the same
 *  files.
 */
export type Session = {
	/**  The queue in library order, exactly as the queue store holds it. */
	queuePaths?: string[],
	/**
	 *  The shuffle permutation, kept so relaunching mid-shuffle continues the
	 *  order you were part-way through instead of drawing a new one.
	 */
	shuffleOrder?: number[],
	/**  Index into `queue_paths`, or -1 when nothing was playing. */
	cursor?: number,
	shuffle?: boolean,
	repeat?: RepeatMode,
	positionSecs?: number,
	volume?: number,
};

export type SyncOutcome = {
	uploaded: number,
	downloaded: number,
	upToDate: number,
	bytesUp: number,
	bytesDown: number,
	/**  Files that failed, with the reason - the rest of the sync still runs */
	failures: string[],
};

export type Theme = {
	background: string,
	sidebarBackground: string,
	playerBarBackground: string,
	cardBackground: string,
	cardHover: string,
	accentPrimary: string,
	accentSecondary: string,
	textPrimary: string,
	textSecondary: string,
	divider: string,
	progressTrack: string,
	progressFill: string,
	karaokeInactiveLine: string,
	karaokeActiveLine: string,
	karaokeActiveWordHighlight: string,
};

/**
 *  Where the window's colours come from: the palette the user picked by hand,
 *  or the desktop shell's own scheme.
 */
export type ThemeSource = "manual" | "system";

export type Track = {
	id: number,
	path: string,
	title: string,
	artist: string | null,
	album: string | null,
	duration_secs: number | null,
	track_no: number | null,
	is_favorite: boolean,
	/**  Playback speed multiplier without pitch shift; 1.0 = normal. */
	tempo: number,
	/**
	 *  How many times this has been listened to far enough to count. See
	 *  `lib/playThreshold` on the frontend for what "far enough" means.
	 */
	play_count: number,
	/**
	 *  Unix seconds, or null if never played. `f64` rather than `i64` because
	 *  specta refuses to export 64-bit integers (they lose precision in JS) -
	 *  and a second count is exact in a double for the next several million
	 *  years, so nothing is given up by saying so.
	 */
	last_played_at: number | null,
	/**
	 *  Unix seconds of when the library first saw the file. Backfilled from the
	 *  file's mtime for rows that predate the column.
	 */
	added_at: number,
};

/**  The four swatches the Now Playing background gradient is built from. */
export type TrackPalette = {
	vibrant: string,
	darkVibrant: string,
	muted: string,
	darkMuted: string,
};

