// Re-exports the Tauri Specta-generated types so the rest of the app has one
// stable import path even though `bindings.ts` is regenerated by the Rust build.
export type {
  Appearance,
  Hotkeys,
  LrcLine,
  LrcWord,
  Lyrics,
  PlaybackError,
  PlaybackSettings,
  PlaybackTick,
  Playlist,
  RepeatMode,
  ReplayGainMode,
  ReplayGainSettings,
  S3Config,
  ScanReport,
  Session,
  SyncOutcome,
  Theme,
  ThemeSource,
  Track,
  TrackPalette,
} from "./bindings";
